# Automatically run `cargo update` periodically

---
name: Bump dependencies in Cargo.lock
on:
  schedule:
    # Run weekly
    - cron: '0 0 * * Sun'
  workflow_dispatch:
    # Needed so we can run it manually
permissions:
  contents: read
defaults:
  run:
    shell: bash
env:
  CARGO_UPGRADES_VER: --version=1.3.6
  PR_TITLE: Weekly `cargo update`
  PR_MESSAGE: |
    In addition to the semver-compatible updates in this PR,
    the following major upgrades are also available:

jobs:
  update:
    name: update dependencies
    runs-on: ubuntu-latest
    outputs:
      lock: ${{ steps.lock.outputs.lock }}
      upgrades: ${{ steps.upgrades.outputs.upgrades }}
    steps:
      - name: checkout the source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: recursive
      - name: install the latest nightly
        run: |
          rustup toolchain install nightly
          rustup default nightly
      - name: install cargo-upgrades
        run: cargo install -f cargo-upgrades $CARGO_UPGRADES_VER

      - name: cargo update
        run: cargo update
      - name: output Cargo.lock for use in PR
        id: lock
        run: |
          # Read Cargo.lock into an output
          LOCK="$(cat Cargo.lock)"
          # Escape LF/CR because outputs must be a single line
          LOCK="${LOCK//'%'/'%25'}"
          LOCK="${LOCK//$'\n'/'%0A'}"
          LOCK="${LOCK//$'\r'/'%0D'}"
          echo "lock=${LOCK}" >> "$GITHUB_OUTPUT"

      - name: cargo upgrades
        # cargo-upgrade exits 7 if upgrades are available, ignore that
        run: cargo upgrades > cargo_upgrades.stdout || exit 0
      - name: output upgrades for use in PR
        id: upgrades
        run: |
          # Read cargo_upgrades.stdout into an output
          # Convert absolute paths to relative paths
          UPGRADES="$(sed "s#$(pwd)/##" cargo_upgrades.stdout)"
          # Escape LF/CR because outputs must be a single line
          UPGRADES="${UPGRADES//'%'/'%25'}"
          UPGRADES="${UPGRADES//$'\n'/'%0A'}"
          UPGRADES="${UPGRADES//$'\r'/'%0D'}"
          echo "upgrades=${UPGRADES}" >> "$GITHUB_OUTPUT"

  pr:
    name: amend PR
    needs: update
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: checkout the source code
        uses: actions/checkout@v3

      - name: get Cargo.lock from update job
        env:
          LOCK: ${{ needs.update.outputs.lock }}
        run: |
          # Un-escape
          LOCK="${LOCK//'%0D'/$'\r'}"
          LOCK="${LOCK//'%0A'/$'\n'}"
          LOCK="${LOCK//'%25'/'%'}"
          # Write to file
          echo "${LOCK}" > Cargo.lock
      - name: craft PR body
        env:
          UPGRADES: ${{ needs.update.outputs.upgrades }}
        run: |
          # Un-escape
          UPGRADES="${UPGRADES//'%0D'/$'\r'}"
          UPGRADES="${UPGRADES//'%0A'/$'\n'}"
          UPGRADES="${UPGRADES//'%25'/'%'}"

          echo "${PR_MESSAGE}" > body.md
          echo '```txt' >> body.md
          echo "${UPGRADES}" >> body.md
          echo '```' >> body.md

      - name: edit and reopen existing pull request
        id: edit
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit cargo_update --title "${PR_TITLE}" --body-file body.md --repo $GITHUB_REPOSITORY
          gh pr reopen cargo_update --repo $GITHUB_REPOSITORY
      - name: commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git switch -C cargo_update
          git add ./Cargo.lock
          git commit --no-verify -m "cargo update"
          git push --no-verify -f -u origin cargo_update
      - name: open new pull request
        # Only run if there wasn't an existing PR
        if: steps.edit.outcome != 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr create --title "${PR_TITLE}" --body-file body.md --repo $GITHUB_REPOSITORY
